version: '2'

services:
  service1:
    build: service1
    image: bmancini55/service1-swarm
    networks:
    - my-network
    ports:
    - "8080"
  manager:
    build: manager
    image: bmancini55/manager-swarm
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    networks:
    - my-network
    ports:
    - "4111:8080"
  elasticsearch:
    image: elasticsearch:5
    networks:
    - my-network
    ports:
    - "9200:9200"
    - "9300:9300"

networks:
  my-network:
    driver: overlay
